### ISSUE TITLE
Unnamed Green Cells look exactly like viruses...

### ISSUE THREAD

**Issue by PatheticMustan** [owenashurst/agar.io-clone#522] opened 2018-10-10 17:38 UTC
So is probably a low priority problem, but green unnamed cells look exactly like viruses. (#475) It's just an enhancement that could be added. :p

**Comment by owenashurst** [comment] 2023-05-13 15:13
Duplicate of https://github.com/owenashurst/agar.io-clone/issues/475

**Closed by owenashurst** 2023-05-13 15:13 UTC
